FROM oven/bun:1 AS build

WORKDIR /app

COPY ./web/package.json ./web/bun.lock ./

RUN bun install --frozen-lockfile

COPY ./web .

RUN bun run build

FROM nginx:alpine AS production

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./conf/web.nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
